### ISSUE TITLE
Setup instructions for Linux

### ISSUE THREAD

**Issue by iamprakkie** [aws-samples/cdk-eks-blueprints-patterns#107]
Provide setup steps to use the patterns to deploy and also to develop in Linux in addition to Mac.

**Comment by shapirov103** [comment]
@iamprakkie I agree we should add instructions to the README. You can use [these](https://aws-quickstart.github.io/cdk-eks-blueprints/getting-started/) instructions for Linux (Ubuntu/Debian). For AL2/RHEL (fedora based) we don't have the instructions yet, despite the fact that we use them internally for development.

**Comment by elamaran11** [comment]
@iamprakkie Please check [this](https://github.com/aws-observability/cdk-aws-observability-accelerator/blob/main/README.md) readme to make it work for linux. We will adding this to blueprints soon

**Comment by elamaran11** [comment]
Ubuntu instructions are added. Closing this issue
