### ISSUE TITLE
This blueprint does not spin up any pods/nodes

### ISSUE THREAD

**Issue by omi-jbrivero** [aws-samples/cdk-eks-blueprints-patterns#175]
Hello, 

I was trying to setup for the first time: https://aws.amazon.com/blogs/opensource/building-developer-portals-with-backstage-and-amazon-eks-blueprints/

This blueprint does not spin up any pods/nodes but turns out it does not spin up any nodes.

Are anyone also experiencing same issue?

Thanks!

**Comment by freschri** [comment]
> Hello,
> 
> I was trying to setup for the first time: https://aws.amazon.com/blogs/opensource/building-developer-portals-with-backstage-and-amazon-eks-blueprints/
> 
> This blueprint does not spin up any pods/nodes but turns out it does not spin up any nodes.
> 
> Are anyone also experiencing same issue?
> 
> Thanks!

thanks @omi-jbrivero could you please expand on the problem description? e.g. what's the output log? thanks

**Comment by omi-jbrivero** [comment]
I am getting a 503 error, upon checking EKS cluster, there is no running nodes/pods.
