### ISSUE TITLE
JupyterHub Pattern

### ISSUE THREAD

**Issue by youngjeong46** [aws-samples/cdk-eks-blueprints-patterns#43]
**Is your feature request related to a problem? Please describe.**
With JupyterHub addon being created, it will be good to create a pattern around it.

**Describe the solution you'd like**
JupyterHub pattern will consist of the following:
- Authentication model (using Cognito)
- EBS as persistent storage (using EBS CSI Driver Addon) (possibly also EFS)
- Load Balancing with Load Balancer controller Addon
- Certificates for HTTPS connection
- R53 for DNS resolution

**Comment by elamaran11** [comment]
@youngjeong46 I know this is implemented. Cann we close this?

**Comment by youngjeong46** [comment]
Yes. Will close.
