### ISSUE TITLE
Blueprints pattern to deploy stateful application using ACK and GitOps

### ISSUE THREAD

**Issue by rameshv29** [aws-samples/cdk-eks-blueprints-patterns#47]
**Describe the solution you'd like**
A new blueprints pattern to demonstrate the deployment of a containerized stateful application which has Aurora serverless v2 and MemoryDB for Redis using AWS Controller for Kubernetes (ACK) and GitOps.

**Comment by elamaran11** [comment]
@rameshv29 Are we planning to make progress on this pattern or we can close it?
