### ISSUE TITLE
Multi Region EKS Cluster Blueprints Pattern with Database

### ISSUE THREAD

**Issue by rameshv29** [aws-samples/cdk-eks-blueprints-patterns#48]
**Describe the solution you'd like**
A new blueprints pattern to demonstrate the deployment of a multi-region EKS cluster with a containerized stateful application which has Aurora Global database and demonstrate the failover.

**Comment by elamaran11** [comment]
@rameshv29 Are we planning to make progress on this pattern or we can close it?
