### ISSUE TITLE
How to pass existing VPC in pipeline stack using ParameterStore

### ISSUE THREAD

**Issue by rverma-nsl** [aws-samples/cdk-eks-blueprints-patterns#55]
**Is your feature request related to a problem? Please describe.**
When defining the pipeline stack by following the guide https://github.com/aws-samples/cdk-eks-blueprints-patterns/blob/main/lib/pipeline-multi-env-gitops/index.ts, I want to provide my existing VPC configuration. I have stored my VPC detail in the target account parameter store which I want to fetch and pass to the blueprint.

**Describe the solution you'd like**
https://github.com/aws-samples/cdk-eks-blueprints-patterns/blob/a2793552ea4ac160d124fd76eddf606fe5244207/lib/pipeline-multi-env-gitops/index.ts#L110

I want to pass resource provider as 
```
   const vpcProvider = new blueprints.VpcProvider(ssm.StringParameter.valueFromLookup(scope, '/devops/network/workspace/vpc/id'))
        const blueprint = blueprints.EksBlueprint.builder()
          .version(clusterVersion)
          .resourceProvider(blueprints.GlobalResources.Vpc, vpcProvider)
          .clusterProvider(
            // blueMNG,
            greenMNG,
          )
```

This compiles fine, however this give an error
```
2023-01-14 01:57:08.098  ERROR [main bin/main.ts:70 undefined.<anonymous>] 
 Error  App at '' should be created in the scope of a Stack, but no Stack found
error stack:
• stack.js:1 _lookup
    node_modules/aws-cdk-lib/core/lib/stack.js:1:4048

• stack.js:1 of
    node_modules/aws-cdk-lib/core/lib/stack.js:1:3783

• context-provider.js:2 getValue
    node_modules/aws-cdk-lib/core/lib/context-provider.js:2:451

• parameter.js:1 valueFromLookup
    node_modules/aws-cdk-lib/aws-ssm/lib/parameter.js:1:6365

• index.ts:109 buildAsync
    lib/pipeline-multi-env-gitops/index.ts:109:76

• task_queues:95 processTicksAndRejections
    node:internal/process/task_queues:95:5

```

Wondering what is the right way to handle this?

**Comment by elamaran11** [comment]
@rverma-nsl Please check the VPC CNI addon documentation in EKS Blueprints for how to pass existing VPC, this implemented already. Please reachout for further issues. Closing this issue.
