### ISSUE TITLE
Support for Amazon GuardDuty as a deployment pattern/construct

### ISSUE THREAD

**Issue by parkand1** [aws-samples/cdk-eks-blueprints-patterns#66]
**Is your feature request related to a problem? Please describe.**
The ability to leverage Amazon GuardDuty to continuously monitor and profile Amazon EKS cluster activity to identify malicious or suspicious behavior to underlying container workloads

**Describe the solution you'd like**
To have Amazon GuardDuty as a EKS Blueprints deployment pattern to address potential security findings that includes container details such as pod ID, container image ID, and associated tags. 

**Describe alternatives you've considered**
There are open-source products that address continuous monitoring but would like to use Amazon native services.

**Additional context**
Ideally by leveraging such pattern, the pattern will enable GuardDuty in the various AWS accounts being operated in along with automating the ability for sending notifications via email based on threats found in Guard Duty

**Comment by elamaran11** [comment]
@parkand1 Can we close this. We merged a PR for GuardDUty
