### ISSUE TITLE
VPC Lattice Pattern

### ISSUE THREAD

**Issue by nrajb** [aws-samples/cdk-eks-blueprints-patterns#85]
**Is your feature request related to a problem? Please describe.**
Amazon VPC Lattice being generally available, with Amazon EKS, it would be good to have a pattern to leverage Amazon VPC Lattice through the use of the AWS [Gateway API](https://gateway-api.sigs.k8s.io/) Controller, an implementation of the Kubernetes Gateway API.

**Describe the solution you'd like**
VPC Lattice Pattern could provide following, but not limited to:
- Service Directory
- Networks
- Resource and Auth Policies
- Gateways
- Kubernetes multi-cluster connectivity: Pattern where VPC Lattice handles connectivity between clusters without needing sidecars

**Additional context**
[AWS Gateway API Controller User Guide](https://www.gateway-api-controller.eks.aws.dev/#aws-gateway-api-controller-user-guide)

**Comment by shapirov103** [comment]
@nrajb this pattern is very desirable, we also welcome contributions. I assume [framework](https://github.com/aws-quickstart/cdk-eks-blueprints/issues) level support will be needed to make it happen, the pattern should use Gateway API Controller installation (addon) and potentially GitOps driven mesh/ingress specifications. I suppose it would make most sense in a multi-account setup.
